# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RecognitionServer.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='RecognitionServer.proto',
  package='recognition',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b(
    '\n\x17RecognitionServer.proto\x12\x0brecognition\"6\n\x19GestureRecognitionRequest\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"W\n\x17GestureRecognitionReply\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x02 \x01(\x03\x12\x0e\n\x06\x65rrMsg\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x05\x32{\n\x11RecognitionServer\x12\x66\n\x12GestureRecognition\x12&.recognition.GestureRecognitionRequest\x1a$.recognition.GestureRecognitionReply(\x01\x30\x01\x62\x06proto3')
)

_GESTURERECOGNITIONREQUEST = _descriptor.Descriptor(
  name='GestureRecognitionRequest',
  full_name='recognition.GestureRecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='recognition.GestureRecognitionRequest.ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='recognition.GestureRecognitionRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=94,
)

_GESTURERECOGNITIONREPLY = _descriptor.Descriptor(
  name='GestureRecognitionReply',
  full_name='recognition.GestureRecognitionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='recognition.GestureRecognitionReply.ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errCode', full_name='recognition.GestureRecognitionReply.errCode', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='recognition.GestureRecognitionReply.errMsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='recognition.GestureRecognitionReply.result', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['GestureRecognitionRequest'] = _GESTURERECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['GestureRecognitionReply'] = _GESTURERECOGNITIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GestureRecognitionRequest = _reflection.GeneratedProtocolMessageType('GestureRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR': _GESTURERECOGNITIONREQUEST,
  '__module__': 'RecognitionServer_pb2'
  # @@protoc_insertion_point(class_scope:recognition.GestureRecognitionRequest)
})
_sym_db.RegisterMessage(GestureRecognitionRequest)

GestureRecognitionReply = _reflection.GeneratedProtocolMessageType('GestureRecognitionReply', (_message.Message,), {
  'DESCRIPTOR': _GESTURERECOGNITIONREPLY,
  '__module__': 'RecognitionServer_pb2'
  # @@protoc_insertion_point(class_scope:recognition.GestureRecognitionReply)
})
_sym_db.RegisterMessage(GestureRecognitionReply)

_RECOGNITIONSERVER = _descriptor.ServiceDescriptor(
  name='RecognitionServer',
  full_name='recognition.RecognitionServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=185,
  serialized_end=308,
  methods=[
    _descriptor.MethodDescriptor(
      name='GestureRecognition',
      full_name='recognition.RecognitionServer.GestureRecognition',
      index=0,
      containing_service=None,
      input_type=_GESTURERECOGNITIONREQUEST,
      output_type=_GESTURERECOGNITIONREPLY,
      serialized_options=None,
    ),
  ])
_sym_db.RegisterServiceDescriptor(_RECOGNITIONSERVER)

DESCRIPTOR.services_by_name['RecognitionServer'] = _RECOGNITIONSERVER

# @@protoc_insertion_point(module_scope)
